/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeIcon: typeof import('./src/components/icons/CodeIcon.vue')['default']
    Forum: typeof import('./src/components/Forum.vue')['default']
    ForumIcon: typeof import('./src/components/icons/ForumIcon.vue')['default']
    ForumItem: typeof import('./src/components/ForumItem.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    LeftArrowIcon: typeof import('./src/components/icons/LeftArrowIcon.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    ReportButton: typeof import('./src/components/ReportButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}

// For TSX support
declare global {
  const CodeIcon: typeof import('./src/components/icons/CodeIcon.vue')['default']
  const Forum: typeof import('./src/components/Forum.vue')['default']
  const ForumIcon: typeof import('./src/components/icons/ForumIcon.vue')['default']
  const ForumItem: typeof import('./src/components/ForumItem.vue')['default']
  const HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
  const LeftArrowIcon: typeof import('./src/components/icons/LeftArrowIcon.vue')['default']
  const MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
  const MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
  const Navbar: typeof import('./src/components/Navbar.vue')['default']
  const ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
  const ReportButton: typeof import('./src/components/ReportButton.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
  const UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
}